### PR TITLE
Added log level to Breadcrump

### PR DESCRIPTION
**Pull request by easypeet**
Sentry-breadcrump-level-example

### CODE REVIEW

**Comment by johanhelsing** [comment]
Just tested this one of my personal projects, and it works like a charm. This makes it so much easier to make sense of logs on projects that are a bit spammy with info messages 😊

Code also looks good to me 👍

**Comment by bruno-garcia** [comment]
This is already happening on our new SDK: https://github.com/getsentry/sentry-unity/blob/9d829236170a8864b8d4b4aab2a6520b9e91739b/src/Sentry.Unity/SentryInitialization.cs#L168

Cross posting this answer, from the other PR:
https://github.com/getsentry/sentry-unity-lite/pull/14#issuecomment-820614210

> We'd really appreciate PRs on the new repo. And additional tests and validation of the SDK. That said, given that changes to this code base require testing, validation and support from our end, at this point we're not accepting PRs.

**Comment by johanhelsing** [comment]
Just realized this is backwards incompatible because it changes the signature of `SentrySdk.AddBreadcrumb(string message, string level)`.

**Comment by bruno-garcia** [comment]
Closing this as we're not planning to add features to this code base.
This feature exists on the current Sentry SDK for Unity and we'd really appreciate feedback: https://github.com/getsentry/sentry-unity

**Pull request closed without merging**
